---
# This playbook uses the ping module to test connectivity to Linux hosts
- name: Ping
  hosts: 192.168.33.10
  remote_user: ubuntu

  tasks:
  - name: ping
    ping:
  - name: echo
    shell: echo Hello World! > hello_world
