---
# This playbook uses the ping module to test connectivity to Linux hosts
- name: Files
  hosts: 192.168.33.10
  remote_user: ubuntu

  tasks:
  - name: have ansible create a directory
    file:
      path: /tmp/demo_server
      state: directory
      recurse: yes
